server:
  shutdown: graceful
debug: false

spring:
  memory-monitor-enable: false
  check:
    server-uri: http://127.0.0.1:9000
    core-pool-size: 2
    maximum-pool-size: 20
    max-retry-times: 1000
    retry-interval-times: 10000
    maximum-topic-size: 30
    maximum-table-slice-size: 100000
  lifecycle:
    timeout-per-shutdown-phase: 5
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      linger.ms: 10
      max.in.flight.requests.per.connection: 5
    producer:
      retries: 3
      acks: all
      batch-size: 2097152 # 2M
      buffer-memory: 67108864 # 64M
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: checkgroup
      enable-auto-commit: true
      auto-commit-interval: 100
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      fetch-min-size: 1
      max-poll-records: 20000
      fetch-max-bytes: 536870912  # 512M
  mvc:
    async:
      request-timeout: 60000

feign:
  okhttp:
    enabled: true

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  group-configs:
    - group: stores
      paths-to-match: /extract/**
